apiVersion: v1
kind: Service
metadata:
  name: capacity-control-service
spec:
  selector:
    app: capacity-control
  ports:
    - protocol: TCP
      port: 5122
      targetPort: 5122   
  type: LoadBalancer